name: PiInfinteChest
version: 1.0
main: org.piegottin.piInfinteChest.PiInfinteChest
api-version: 1.21
commands:
  infinitechest:
    description: Gives the player an infinite chest.
    usage: /infinitechest
    permission: piinfinitechest.use
permissions:
  piinfinitechest.use:
    default: true
